Repository FlySamryong/Meodeun_Daeyeo_backend, pull requests merged in 2024-11, with the labels that each got.

#48 [Feat] ✨ : 반납을 알려주기위해 채팅방에 메세지 보내기 구현
  src/main/java/samryong/domain/chat/converter/ChatMessageConverter.java
  src/main/java/samryong/domain/chat/converter/ChatRoomConverter.java
  src/main/java/samryong/domain/chat/dto/ChatMessageDTO.java
  src/main/java/samryong/domain/chat/dto/ChatRoomDTO.java
  src/main/java/samryong/domain/chat/entity/ChatMessage.java
  src/main/java/samryong/domain/chat/service/ChatRoomServiceImpl.java
  src/main/java/samryong/domain/notice/converter/NoticeConverter.java
  src/main/java/samryong/domain/notice/service/NoticeService.java
  src/main/java/samryong/domain/notice/service/NoticeServiceImpl.java
  src/main/java/samryong/domain/rent/entity/Rent.java
  src/main/java/samryong/domain/rent/service/RentService.java
  src/main/java/samryong/domain/rent/service/impl/RentRequestServiceImpl.java
  src/main/java/samryong/domain/rent/service/impl/RentServiceImpl.java
  src/main/java/samryong/domain/rent/service/listener/RentKeyExpirationListener.java
Labels: :sparkles: Feature

#53 :bug: [Bug] 타임존 오류 수정
  src/main/java/samryong/SamryongApplication.java
Labels: :lady_beetle: BugFix

#60 🐛 [Bug] 송/수신자 간에 rentId가 공유 안되는 문제 수정
  src/main/java/samryong/domain/chat/converter/ChatMessageConverter.java
  src/main/java/samryong/domain/chat/dto/ChatMessageDTO.java
  src/main/java/samryong/domain/chat/entity/ChatMessage.java
  src/main/java/samryong/domain/chat/service/ChatMessageService.java
  src/main/java/samryong/domain/chat/service/ChatMessageServiceImpl.java
  src/main/java/samryong/domain/rent/service/impl/RentExpirationServiceImpl.java
  src/main/java/samryong/domain/rent/service/impl/RentRequestServiceImpl.java
  src/main/java/samryong/domain/rent/service/impl/RentReturnServiceImpl.java
Labels: :lady_beetle: BugFix

#61 :sparkles: [Feat] 채팅 메시지 타임 Zone KST로 변경
  src/main/java/samryong/domain/chat/TimeZoneUtil.java
  src/main/java/samryong/domain/chat/converter/ChatMessageConverter.java
Labels: :lady_beetle: BugFix, :hammer: Refactor

#62 🐛 : [Bug] 채팅 송/수신 메시지 간 채팅 시간 차이 오류 수정
  src/main/java/samryong/domain/chat/converter/ChatMessageConverter.java
Labels: :lady_beetle: BugFix

#63 :bug; [Bug] 채팅방 조회로 인해 몽고 DB에서 Redis로 채팅 메시지 로드 안되는 오류 수정
  src/main/java/samryong/domain/chat/service/ChatRoomServiceImpl.java
Labels: :lady_beetle: BugFix

#66 [Feat] 거주지 등록 api 추가 및 반납 예정 알림 Redis 갱신 오류 수정
  src/main/java/samryong/domain/bank/nonghyup/provider/NonghyupTransactionProvider.java
  src/main/java/samryong/domain/member/controller/MemberController.java
  src/main/java/samryong/domain/member/entity/Member.java
  src/main/java/samryong/domain/member/service/MemberService.java
  src/main/java/samryong/domain/member/service/MemberServiceImpl.java
  src/main/java/samryong/domain/notice/service/NoticeServiceImpl.java
  src/main/java/samryong/domain/rent/service/RentService.java
  src/main/java/samryong/domain/rent/service/impl/RentExpirationServiceImpl.java
  src/main/java/samryong/domain/rent/service/impl/RentServiceImpl.java
  src/main/java/samryong/global/code/GlobalErrorCode.java
Labels: :sparkles: Feature, :lady_beetle: BugFix, :hammer: Refactor

#64 ✨ [Feat] : 찜 기능들 추가 (wishList)
  src/main/java/samryong/domain/item/contorller/ItemController.java
  src/main/java/samryong/domain/item/converter/ItemConverter.java
  src/main/java/samryong/domain/item/converter/WishItemConverter.java
  src/main/java/samryong/domain/item/dto/ItemDTO.java
  src/main/java/samryong/domain/item/entity/WishItem.java
  src/main/java/samryong/domain/item/service/item/ItemService.java
  src/main/java/samryong/domain/item/service/item/ItemServiceImpl.java
  src/main/java/samryong/domain/member/controller/MemberController.java
  src/main/java/samryong/domain/member/entity/Member.java
  src/main/java/samryong/domain/member/repository/MemberRepository.java
  src/main/java/samryong/domain/member/service/MemberService.java
  src/main/java/samryong/domain/member/service/MemberServiceImpl.java
  src/main/java/samryong/domain/notice/service/NoticeServiceImpl.java
  src/main/java/samryong/domain/rent/service/impl/RentRequestServiceImpl.java
Labels: :sparkles: Feature, :hammer: Refactor

#68 :bug: [Bug] 대여 기간 UTC로 반환되는 오류 수정
  src/main/java/samryong/domain/member/service/MemberService.java
  src/main/java/samryong/domain/rent/converter/RentConverter.java
Labels: :sparkles: Feature

#70 :bug: [Bug] 대여 최신 메시지에 가장 오래된 메시지가 반환되는 오류 수정
  src/main/java/samryong/domain/chat/service/ChatMessageServiceImpl.java
  src/main/java/samryong/domain/chat/service/ChatRoomServiceImpl.java
Labels: :lady_beetle: BugFix

#72 :bug: [Bug] recentItemResponseDTO 응답 필드 수정
  src/main/java/samryong/domain/item/contorller/ItemController.java
  src/main/java/samryong/domain/item/converter/ItemConverter.java
  src/main/java/samryong/domain/item/dto/ItemDTO.java
  src/main/java/samryong/domain/item/service/item/ItemServiceImpl.java
  src/main/java/samryong/domain/item/service/recentItem/RecentItemService.java
  src/main/java/samryong/domain/item/service/recentItem/RecentItemServiceImpl.java
Labels: :lady_beetle: BugFix, :hammer: Refactor

#73 :recycle: [Refactor] 프론트 url Cors 허용
  src/main/java/samryong/global/config/WebConfig.java
Labels: :hammer: Refactor
