Repository FlySamryong/Meodeun_Daeyeo_backend, pull requests merged in 2024-09, with the labels that each got.

#9 ✨ [Feat] 카카오 로그인, JWT 인증/인가 로직, 토큰 갱신 로직 구현
  build.gradle
  src/main/java/samryong/auth/controller/AuthController.java
  src/main/java/samryong/auth/converter/KakaoAuthConverter.java
  src/main/java/samryong/auth/dto/AuthResponseDTO.java
  src/main/java/samryong/auth/service/AuthService.java
  src/main/java/samryong/auth/service/AuthServiceImpl.java
  src/main/java/samryong/config/SwaggerConfig.java
  src/main/java/samryong/controller/.gitkeep
  src/main/java/samryong/converter/.gitkeep
  src/main/java/samryong/domain/.gitkeep
  src/main/java/samryong/dto/.gitkeep
  src/main/java/samryong/global/code/GlobalErrorCode.java
  src/main/java/samryong/global/config/QuerydslConfig.java
  src/main/java/samryong/global/config/SchedulerConfig.java
  src/main/java/samryong/global/config/SwaggerConfig.java
  src/main/java/samryong/global/config/WebConfig.java
  src/main/java/samryong/global/exception/ExceptionAdvice.java
  src/main/java/samryong/global/response/ErrorResponse.java
  src/main/java/samryong/member/domain/Member.java
  src/main/java/samryong/member/repository/MemberRepository.java
  src/main/java/samryong/member/service/MemberService.java
  src/main/java/samryong/member/service/MemberServiceImpl.java
  src/main/java/samryong/redis/RedisConfig.java
  src/main/java/samryong/redis/domain/RefreshToken.java
  src/main/java/samryong/redis/repository/RefreshTokenRepository.java
  src/main/java/samryong/redis/service/RefreshTokenService.java
  src/main/java/samryong/repository/.gitkeep
  src/main/java/samryong/security/.gitkeep
  src/main/java/samryong/security/SecurityConfig.java
  src/main/java/samryong/security/filter/ExceptionHandleFilter.java
  src/main/java/samryong/security/filter/JwtAuthenticationFilter.java
  src/main/java/samryong/security/handler/JwtAccessDeniedHandler.java
  src/main/java/samryong/security/handler/JwtAuthenticationFailEntryPoint.java
  src/main/java/samryong/security/provider/JwtTokenProvider.java
  src/main/java/samryong/security/provider/KakaoAuthProvider.java
  src/main/java/samryong/security/resolver/GetTokenArgumentResolver.java
  src/main/java/samryong/security/resolver/annotation/GetToken.java
  src/main/java/samryong/security/userDetail/MemberDetails.java
  src/main/java/samryong/security/userDetail/MemberDetailsService.java
  src/main/java/samryong/service/.gitkeep
  src/main/resources/application-local.yml
  src/main/resources/application-server.yml
Labels: :sparkles: Feature, :hammer: Refactor

#11 Feature/10 extract user
  src/main/java/samryong/auth/controller/AuthController.java
  src/main/java/samryong/auth/converter/KakaoAuthConverter.java
  src/main/java/samryong/global/config/WebConfig.java
  src/main/java/samryong/member/domain/Member.java
  src/main/java/samryong/member/service/MemberService.java
  src/main/java/samryong/member/service/MemberServiceImpl.java
  src/main/java/samryong/security/resolver/AuthMemberArgumentResolver.java
  src/main/java/samryong/security/resolver/annotation/AuthMember.java
Labels: :sparkles: Feature, :white_check_mark: Test, :hammer: Refactor

#15 ✨ [Feat] 농협 계좌이체 기능을 위한 농협 오픈 API와 통신 기능 구현
  src/main/java/samryong/bank/nonghyup/dto/request/BankTransferRequestDTO.java
  src/main/java/samryong/bank/nonghyup/dto/response/CheckOpenFinAccountDirectResponseDTO.java
  src/main/java/samryong/bank/nonghyup/dto/response/DrawingTransferResponseDTO.java
  src/main/java/samryong/bank/nonghyup/dto/response/OpenFinAccountDirectResponseDTO.java
  src/main/java/samryong/bank/nonghyup/dto/response/ReceivedTransferAccountNumberResponseDTO.java
  src/main/java/samryong/bank/nonghyup/dto/response/ResponseHeader.java
  src/main/java/samryong/bank/nonghyup/exception/NonghyupException.java
  src/main/java/samryong/bank/nonghyup/provider/NonghyupTransactionProvider.java
  src/main/java/samryong/global/exception/ExceptionAdvice.java
  src/main/java/samryong/global/response/ErrorResponse.java
  src/main/resources/application-local.yml
  src/main/resources/application-server.yml
Labels: :sparkles: Feature

#16 ✨ [Feat] ChatMessage, ChatRoom, Rent 엔터티, 컨트롤러, 서비스, 리포지터리 추가
  build.gradle
  src/main/java/samryong/SamryongApplication.java
  src/main/java/samryong/chat/controller/ChatController.java
  src/main/java/samryong/chat/domain/ChatMessage.java
  src/main/java/samryong/chat/domain/ChatRoom.java
  src/main/java/samryong/chat/repository/ChatMessageRepository.java
  src/main/java/samryong/chat/repository/ChatRoomRepository.java
  src/main/java/samryong/chat/service/ChatService.java
  src/main/java/samryong/chat/service/ChatServiceImpl.java
  src/main/java/samryong/global/BaseEntity.java
  src/main/java/samryong/rent/domain/Rent.java
  src/main/java/samryong/rent/repository/RentRepository.java
  src/main/java/samryong/rent/service/RentService.java
  src/main/java/samryong/rent/service/RentServiceImpl.java
  src/main/resources/application-local.yml
  src/main/resources/application-server.yml
Labels: :sparkles: Feature

#18 ✨ [Feat] report, location, account 도메인 추가
  src/main/java/samryong/account/domain/Account.java
  src/main/java/samryong/account/repository/AccountRepository.java
  src/main/java/samryong/account/service/AccountService.java
  src/main/java/samryong/account/service/AccountServiceImpl.java
  src/main/java/samryong/location/domain/Location.java
  src/main/java/samryong/location/repository/LocationRepository.java
  src/main/java/samryong/location/service/LocationService.java
  src/main/java/samryong/location/service/LocationServiceImpl.java
  src/main/java/samryong/member/domain/Member.java
  src/main/java/samryong/report/domain/Report.java
  src/main/java/samryong/report/repository/ReportRepository.java
  src/main/java/samryong/report/service/ReportService.java
  src/main/java/samryong/report/service/ReportServiceImpl.java
Labels: :sparkles: Feature

#21 [Feat] Item, Item_Category, Category 추가
  src/main/java/samryong/item/domain/Category.java
  src/main/java/samryong/item/domain/Item.java
  src/main/java/samryong/item/domain/ItemCategory.java
  src/main/java/samryong/item/repository/CategoryRepository.java
  src/main/java/samryong/item/repository/ItemCategoryRepository.java
  src/main/java/samryong/item/repository/ItemRepository.java
  src/main/java/samryong/item/service/category/CategoryService.java
  src/main/java/samryong/item/service/category/CategoryServiceImpl.java
  src/main/java/samryong/item/service/item/ItemService.java
  src/main/java/samryong/item/service/item/ItemServiceImpl.java
  src/main/java/samryong/item/service/itemCategory/ItemCategoryService.java
  src/main/java/samryong/item/service/itemCategory/ItemCategoryServiceImpl.java
Labels: :sparkles: Feature

#20 🐛 [Bug] 연관관계 매핑 오류 수정
  src/main/java/samryong/account/domain/Account.java
  src/main/java/samryong/chat/domain/ChatMessage.java
  src/main/java/samryong/location/domain/Location.java
  src/main/java/samryong/member/domain/Member.java
  src/main/java/samryong/rent/domain/Rent.java
  src/main/java/samryong/report/domain/Report.java
Labels: :lady_beetle: BugFix, :hammer: Refactor

#25 ✨ [Feat] Redis Pub/Sub, STOMP, 웹소켓을 활용하여 채팅 기능 구현
  build.gradle
  src/main/java/samryong/domain/chat/aspect/AuthChatMemberAspect.java
  src/main/java/samryong/domain/chat/aspect/annotation/AuthChatMember.java
  src/main/java/samryong/domain/chat/controller/ChatController.java
  src/main/java/samryong/domain/chat/controller/ChatMessageController.java
  src/main/java/samryong/domain/chat/controller/ChatRoomController.java
  src/main/java/samryong/domain/chat/converter/ChatMessageConverter.java
  src/main/java/samryong/domain/chat/converter/ChatRoomConverter.java
  src/main/java/samryong/domain/chat/dto/ChatMessageDTO.java
  src/main/java/samryong/domain/chat/dto/ChatRoomDTO.java
  src/main/java/samryong/domain/chat/entity/ChatMessage.java
  src/main/java/samryong/domain/chat/redis/RedisPublisher.java
  src/main/java/samryong/domain/chat/redis/RedisSubscriber.java
  src/main/java/samryong/domain/chat/repository/ChatMessageRepository.java
  src/main/java/samryong/domain/chat/repository/ChatRoomRepository.java
  src/main/java/samryong/domain/chat/service/ChatMessageService.java
  src/main/java/samryong/domain/chat/service/ChatMessageServiceImpl.java
  src/main/java/samryong/domain/chat/service/ChatRoomService.java
  src/main/java/samryong/domain/chat/service/ChatRoomServiceImpl.java
  src/main/java/samryong/domain/chat/service/ChatService.java
  src/main/java/samryong/domain/chat/service/ChatServiceImpl.java
  src/main/java/samryong/domain/redis/RedisConfig.java
  src/main/java/samryong/global/code/GlobalErrorCode.java
  src/main/java/samryong/global/config/RedisConfig.java
  src/main/java/samryong/global/config/WebSocketConfig.java
  src/main/java/samryong/global/exception/ExceptionAdvice.java
  src/main/java/samryong/global/interceptor/JwtChannelInterceptor.java
  src/main/java/samryong/security/SecurityConfig.java
Labels: :sparkles: Feature, :gear: Setting

#33 🐛 [Bug] 에러 코드 중복으로 인한 빌드 오류 수정
  src/main/java/samryong/domain/chat/controller/ChatRoomController.java
  src/main/java/samryong/domain/item/dto/ItemDTO.java
  src/main/java/samryong/domain/location/controller/LocationController.java
  src/main/java/samryong/global/code/GlobalErrorCode.java
  src/main/resources/application-server.yml
Labels: :lady_beetle: BugFix, :hammer: Refactor

#35 ✨ [Feat] ElasticSearch를 이용한 물품 검색 API 구현
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/samryong/domain/item/contorller/ItemController.java
  src/main/java/samryong/domain/item/converter/CategoryConverter.java
  src/main/java/samryong/domain/item/converter/ItemConverter.java
  src/main/java/samryong/domain/item/document/CategoryDocument.java
  src/main/java/samryong/domain/item/document/ItemDocument.java
  src/main/java/samryong/domain/item/dto/ItemDTO.java
  src/main/java/samryong/domain/item/repository/elastic/CategoryElasticRepository.java
  src/main/java/samryong/domain/item/repository/elastic/ItemElasticRepository.java
  src/main/java/samryong/domain/item/repository/elastic/ItemElasticRepositoryCustom.java
  src/main/java/samryong/domain/item/repository/elastic/ItemElasticRepositoryImpl.java
  src/main/java/samryong/domain/item/service/category/CategoryService.java
  src/main/java/samryong/domain/item/service/category/CategoryServiceImpl.java
  src/main/java/samryong/domain/item/service/item/ItemService.java
  src/main/java/samryong/domain/item/service/item/ItemServiceImpl.java
  src/main/java/samryong/domain/location/converter/LocationConverter.java
  src/main/java/samryong/domain/location/document/LocationDocument.java
  src/main/java/samryong/domain/location/dto/LocationDTO.java
  src/main/java/samryong/domain/location/repository/LocationElasticRepository.java
  src/main/java/samryong/domain/location/service/LocationServiceImpl.java
  src/main/java/samryong/global/config/ElasticSearchConfig.java
  src/main/resources/application-local.yml
  src/main/resources/elastic/post-setting.json
Labels: :sparkles: Feature
